"""
Per-call cost estimation from OpenRouter pricing.

First consumer of the ``input_price_per_mtok`` / ``output_price_per_mtok`` fields
in ``model_capabilities.yaml`` (regenerated by ``litassist refresh``). Prices are
read from that file, never hardcoded here, so a price change is one refresh away.
"""

from typing import Any, Dict

from .factory import _get_model_capabilities

# Capability prices are quoted in USD per million tokens (refresh converts
# OpenRouter's per-token figure by multiplying by 1e6), so divide token counts
# by this to get the multiplier for a per-mtok price.
MTOK = 1_000_000


def estimate_call_cost(model: str, usage: Dict[str, Any]) -> float:
    """
    Estimate the USD cost of a single LLM call from its token usage.

    Args:
        model: The model id (e.g. ``"openai/o3-pro"``) as it appears in
            ``model_capabilities.yaml``.
        usage: A usage dict from ``LLMClient.complete`` with
            ``prompt_tokens`` / ``completion_tokens`` (missing keys count as 0).

    Returns:
        Estimated cost in USD.

    Raises:
        KeyError: If the model has no capability entry or no price fields. This
            matches the NO FALLBACKS contract of the rest of the LLM layer
            (see ``LLMClientFactory.get_context_window_for_command``); the
            config-integrity tests already assert every configured model is
            present in ``model_capabilities.yaml``. A model whose price fields
            are present but null (``refresh`` writes null when OpenRouter omits a
            price) fails loudly in the arithmetic rather than costing a silent
            zero - no fallback either way.
    """
    caps = _get_model_capabilities()
    if model not in caps:
        raise KeyError(
            f"No capability data for model '{model}'. "
            "Run `litassist refresh` to refresh model_capabilities.yaml."
        )
    entry = caps[model]
    input_price = entry["input_price_per_mtok"]
    output_price = entry["output_price_per_mtok"]
    prompt_tokens = usage.get("prompt_tokens", 0)
    completion_tokens = usage.get("completion_tokens", 0)
    return prompt_tokens / MTOK * input_price + completion_tokens / MTOK * output_price
