"""
Factory for creating LLM client instances with command-specific configurations.

This module contains the LLMClientFactory class that centralizes all model
and parameter configurations for each command.
"""

import logging
import yaml
from pathlib import Path
from typing import Dict, Any

# Import LLMClient - must be imported after the class is defined in client.py
# This creates a one-way dependency: factory -> client
from .client import LLMClient

logger = logging.getLogger(__name__)


def _load_model_configs() -> Dict[str, Any]:
    """
    Load model configurations from YAML.

    Raises:
        FileNotFoundError: If model_configs.yaml doesn't exist
        yaml.YAMLError: If YAML syntax is invalid
        ValueError: If YAML content is invalid
    """
    config_path = Path(__file__).parent / "model_configs.yaml"

    if not config_path.exists():
        raise FileNotFoundError(
            f"Model configuration file not found: {config_path}\n"
            "This file is required for LLM client initialization."
        )

    with open(config_path, 'r', encoding='utf-8') as f:
        configs = yaml.safe_load(f)

    if not configs or not isinstance(configs, dict):
        raise ValueError(
            f"Invalid model configuration in {config_path}: "
            "Expected non-empty dictionary"
        )

    return configs


def _load_model_capabilities() -> Dict[str, Any]:
    """
    Load per-model capability data (context_window, prices, supported_parameters)
    from model_capabilities.yaml. This file is regenerated by
    `litassist refresh` from the OpenRouter /api/v1/models response.
    """
    config_path = Path(__file__).parent / "model_capabilities.yaml"

    if not config_path.exists():
        raise FileNotFoundError(
            f"Model capabilities file not found: {config_path}\n"
            "Run `litassist refresh` to generate it."
        )

    with open(config_path, 'r', encoding='utf-8') as f:
        caps = yaml.safe_load(f)

    if not caps or not isinstance(caps, dict):
        raise ValueError(
            f"Invalid model capabilities in {config_path}: "
            "Expected non-empty dictionary"
        )

    return caps


# Lazy load with caching
_MODEL_CONFIGS_CACHE = None
_MODEL_CAPABILITIES_CACHE = None


def _get_model_configs() -> Dict[str, Any]:
    """Get model configurations with caching."""
    global _MODEL_CONFIGS_CACHE
    if _MODEL_CONFIGS_CACHE is None:
        _MODEL_CONFIGS_CACHE = _load_model_configs()
    return _MODEL_CONFIGS_CACHE


def _get_model_capabilities() -> Dict[str, Any]:
    """Get model capabilities with caching."""
    global _MODEL_CAPABILITIES_CACHE
    if _MODEL_CAPABILITIES_CACHE is None:
        _MODEL_CAPABILITIES_CACHE = _load_model_capabilities()
    return _MODEL_CAPABILITIES_CACHE


class LLMClientFactory:
    """
    Factory class for creating LLMClient instances with command-specific configurations.

    All models use "provider/model" format and route through OpenRouter.

    This centralizes all model and parameter configurations for each command,
    eliminating duplication and providing a single source of truth.

    Configurations are loaded from model_configs.yaml - NO FALLBACKS.
    Missing configurations raise KeyError.
    """

    @classmethod
    def for_command(
        cls, command_name: str, sub_type: str | None = None, **overrides: Any
    ) -> "LLMClient":
        """
        Create an LLMClient configured for a specific command.

        Args:
            command_name: The command name (e.g., 'extractfacts', 'strategy')
            sub_type: Optional sub-type for commands with multiple clients
                     (e.g., 'orthodox', 'unorthodox', 'analysis' for brainstorm,
                      'summary', 'issues' for digest)
            **overrides: Any parameter overrides to apply to the default configuration

        Returns:
            Configured LLMClient instance with command context set

        Examples:
            # Simple command
            client = LLMClientFactory.for_command('extractfacts')

            # Command with sub-type
            client = LLMClientFactory.for_command('brainstorm', 'orthodox')

            # With overrides
            client = LLMClientFactory.for_command('draft', temperature=0.7)
        """
        # Build the configuration key
        if sub_type:
            config_key = f"{command_name}-{sub_type}"
        else:
            config_key = command_name

        # Load configurations from YAML - FAIL FAST on missing config
        configs = _get_model_configs()

        if config_key not in configs:
            available = ", ".join(sorted(configs.keys()))
            raise KeyError(
                f"No model configuration found for command '{config_key}'.\n"
                f"Available configurations: {available}\n"
                f"Add configuration to litassist/llm/model_configs.yaml"
            )

        config = configs[config_key].copy()

        # Extract special flags
        enforce_citations = config.pop("enforce_citations", False)
        disable_tools = config.pop("disable_tools", False)

        # Apply any provided overrides
        config.update(overrides)

        # Extract model from config
        model = config.pop("model")

        # Create the LLM client with remaining config as parameters
        client = LLMClient(model, **config)

        # Set the command context
        client.command_context = config_key

        # Set citation enforcement flag - explicitly set both True and False
        client._enforce_citations = enforce_citations
        client._disable_tools = disable_tools

        return client

    @classmethod
    def get_model_for_command(
        cls, command_name: str, sub_type: str | None = None
    ) -> str:
        """
        Get the model name configured for a specific command.

        Useful for logging or debugging purposes.

        Args:
            command_name: The command name
            sub_type: Optional sub-type

        Returns:
            Model name string
        """
        config_key = f"{command_name}-{sub_type}" if sub_type else command_name
        configs = _get_model_configs()

        if config_key not in configs:
            available = ", ".join(sorted(configs.keys()))
            raise KeyError(
                f"No model configuration found for command '{config_key}'.\n"
                f"Available configurations: {available}"
            )

        return configs[config_key]["model"]

    @classmethod
    def get_context_window_for_command(
        cls, command_name: str, sub_type: str | None = None
    ) -> int:
        """
        Get the input-context window (in tokens) for the model configured for
        a given command.

        Capability data comes from model_capabilities.yaml, which is regenerated
        from OpenRouter by `litassist refresh`. No fallbacks: a missing model
        id raises KeyError.
        """
        model_id = cls.get_model_for_command(command_name, sub_type)
        caps = _get_model_capabilities()
        if model_id not in caps:
            available = ", ".join(sorted(caps.keys()))
            raise KeyError(
                f"No capability data for model '{model_id}' "
                f"(needed by command '{command_name}').\n"
                f"Available models: {available}\n"
                "Run `litassist refresh` to refresh."
            )
        return int(caps[model_id]["context_window"])

    # Conservative chars-per-token ratio for English legal text. Char-count
    # is a safe over-estimate of token count, so derived char budgets fit
    # comfortably inside the actual model token window.
    CHARS_PER_TOKEN: float = 3.5

    @classmethod
    def get_input_budget_for_command(
        cls,
        command_name: str,
        sub_type: str | None = None,
        fraction: float = 0.80,
    ) -> int:
        """
        Get a recommended input-size budget in CHARACTERS for a command.

        Computed as `context_window_tokens * CHARS_PER_TOKEN * fraction`.
        Use the returned value as a file-size cap or a "context is getting
        large" warning threshold instead of hardcoding magic numbers. The
        window is a single shared budget (input + reasoning + output must fit),
        so `1 - fraction` is the worst-case (densest text, ~3.5 chars/token)
        reserve for system prompt + reasoning + completion. The default 0.80
        leaves >=20% of the window -- ~40k tokens on a 200k-window model and
        >=200k tokens on the 1M/2M-window models, comfortably above any
        command's observed output+reasoning. The budget already tracks the
        routed model's window from `model_capabilities.yaml`, so it scales when
        `litassist refresh` updates a model. Tighten with a smaller `fraction`
        only for a command whose own output is unusually large.

        Args:
            command_name: The command name.
            sub_type: Optional sub-type passed through to the underlying
                capability lookup.
            fraction: Fraction of the model's input window to offer to
                user-supplied content (default 0.80).

        Returns:
            Recommended input budget in characters.
        """
        window_tokens = cls.get_context_window_for_command(command_name, sub_type)
        return int(window_tokens * cls.CHARS_PER_TOKEN * fraction)

    @classmethod
    def list_configurations(cls) -> Dict[str, Dict[str, Any]]:
        """
        List all available command configurations.

        Returns:
            Dictionary of all command configurations
        """
        return _get_model_configs().copy()
