# Jekyll configuration for LitAssist Documentation
# https://litassist.github.io

# Site Settings
title: LitAssist Documentation
description: >-
  Comprehensive legal workflow automation tool for Australian legal practice.
  Automate litigation support with AI-powered research, analysis, and drafting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://litassist.github.io" # the base hostname & protocol for your site

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Theme customization
minima:
  skin: auto
  date_format: "%b %-d, %Y"

# Navigation
header_pages:
  - index.md
  - docs/user/LitAssist_User_Guide.md
  - docs/development/ARCHITECTURE.md
  - installation.md
  - api-reference.md

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - logs/
  - test-scripts/
  - tests/
  - examples/
  - '*.pyc'
  - '*.egg-info'
  - 'config.yaml'
  - 'config.yaml.template'
  - requirements*.txt
  - setup.py
  - pytest.ini
  - MANIFEST.in

# Markdown Processing
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    block:
      line_numbers: true

# Collections for organized documentation
collections:
  user_guide:
    output: true
    permalink: /guide/:name
  api:
    output: true
    permalink: /api/:name
  development:
    output: true
    permalink: /dev/:name

# Default values
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "user_guide"
    values:
      layout: "guide"
  - scope:
      path: ""
      type: "api"
    values:
      layout: "api"
  - scope:
      path: ""
      type: "development"
    values:
      layout: "development"

# SEO and social
twitter:
  username: litassist
  card: summary

author:
  name: LitAssist Team
  email: support@litassist.io

# Analytics (add your tracking ID when ready)
# google_analytics: UA-XXXXXXXXX-X

# Repository
repository: litassist/litassist