"""
Refresh per-model capability data from OpenRouter.

Reads distinct model ids from model_configs.yaml, fetches the OpenRouter
/api/v1/models response, and writes a deterministic, sorted YAML mapping
each model id to its context_window, prices, and supported_parameters.

Exits non-zero if any model in model_configs.yaml is missing from the
OpenRouter response (catches silent deprecation).
"""

import json
import sys
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List

import click
import yaml

OPENROUTER_MODELS_URL = "https://openrouter.ai/api/v1/models"


def _distinct_model_ids(configs: Dict[str, Any]) -> List[str]:
    return sorted({
        entry["model"]
        for entry in configs.values()
        if isinstance(entry, dict) and "model" in entry
    })


def _fetch_openrouter_models(url: str, timeout: int = 30) -> Dict[str, Any]:
    req = urllib.request.Request(
        url, headers={"User-Agent": "litassist/refresh"}
    )
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return json.load(resp)


def _build_capabilities(
    model_ids: List[str], or_data: Dict[str, Any]
) -> Dict[str, Dict[str, Any]]:
    by_id = {entry["id"]: entry for entry in or_data.get("data", [])}

    missing = [m for m in model_ids if m not in by_id]
    if missing:
        raise click.ClickException(
            "Models in model_configs.yaml not found on OpenRouter:\n  - "
            + "\n  - ".join(missing)
        )

    capabilities: Dict[str, Dict[str, Any]] = {}
    for mid in sorted(model_ids):
        entry = by_id[mid]
        pricing = entry.get("pricing") or {}
        prompt = pricing.get("prompt")
        completion = pricing.get("completion")
        capabilities[mid] = {
            "context_window": int(entry["context_length"]),
            "input_price_per_mtok": (
                round(float(prompt) * 1_000_000, 4) if prompt is not None else None
            ),
            "output_price_per_mtok": (
                round(float(completion) * 1_000_000, 4)
                if completion is not None
                else None
            ),
            "supported_parameters": sorted(entry.get("supported_parameters") or []),
        }
    return capabilities


def _write_capabilities_yaml(
    output_path: Path, capabilities: Dict[str, Dict[str, Any]]
) -> None:
    header = (
        "---\n"
        "# Auto-generated by `litassist refresh`.\n"
        f"# Last regenerated: {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}\n"
        f"# Source: {OPENROUTER_MODELS_URL}\n"
        "# DO NOT EDIT MANUALLY -- run `litassist refresh`.\n"
        "\n"
    )
    body = yaml.safe_dump(capabilities, sort_keys=True, default_flow_style=False)
    output_path.write_text(header + body)


@click.command()
def refresh() -> None:
    """
    Refresh per-model capability data from OpenRouter.

    Updates litassist/llm/model_capabilities.yaml with each configured model's
    context window, input/output prices, and supported parameters. Run after
    swapping models in model_configs.yaml or when OpenRouter announces
    pricing / context-window changes.
    """
    from litassist.llm.factory import _load_model_configs

    configs = _load_model_configs()
    model_ids = _distinct_model_ids(configs)
    click.echo(
        f"Refreshing capabilities for {len(model_ids)} models "
        f"from {OPENROUTER_MODELS_URL}"
    )

    try:
        or_data = _fetch_openrouter_models(OPENROUTER_MODELS_URL)
    except urllib.error.URLError as exc:
        raise click.ClickException(
            f"Failed to fetch {OPENROUTER_MODELS_URL}: {exc}"
        )

    capabilities = _build_capabilities(model_ids, or_data)

    factory_dir = Path(__file__).resolve().parents[2] / "llm"
    output_path = factory_dir / "model_capabilities.yaml"
    _write_capabilities_yaml(output_path, capabilities)
    click.echo(f"Wrote {output_path} ({len(capabilities)} models)")
    sys.stdout.flush()
