name: Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
    
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements-ci.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install minimal dependencies
      timeout-minutes: 10
      run: |
        pip install --upgrade pip
        pip install -r requirements-ci.txt
    
    - name: Run tests
      run: |
        pytest tests/unit -v
    
    - name: Run black check
      continue-on-error: true
      run: |
        black --check litassist tests